---
title: pandainfo.org
timezone: Europe/Vienna
collections:
  books:
    title: Books
    output: true
    permalink: "/:collection/:path/"
  events:
    title: Events
    output: true
    permalink: "/:collection/:path/"
  news:
    title: News
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: false
- scope:
    path: ''
    type: books
  values:
    layout: single
    read_time: true
    author_profile: true
    share: true
    comments: false
    sidebar:
      nav: books
- scope:
    path: ''
    type: events
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: news
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: about
  values:
    layout: single
    author_profile: true
    share: true
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
locale: de
title_separator: "\U0001F43E"
name: pandainfo.org
description: "assoziation panda! \U0001F43E Verein zur Förderung des kritischen literarischen
  Diskurses"
repository: redtux/pandainfo.org
teaser: "/assets/images/teaser-placeholder-630x200.jpg"
masthead_title: pandainfo.org
breadcrumbs: true
words_per_minute: 190
search: true
search_full_content: true
search_provider: lunr
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: redtux
facebook:
  username: radicalbookstore
  app_id: 
  publisher: 
og_image: "/assets/images/panda-avatar.png"
social:
  type: 
  name: 
  links: 
author:
  name: pandainfo.org
  avatar: "/assets/images/panda-avatar.png"
  bio: "assoziation panda! \U0001F43E Verein zur Förderung des kritischen literarischen
    Diskurses"
  location: Vienna, Austria
  links:
  - label: pandainfo.org
    icon: fas fa-fw fa-link
    url: https://pandainfo.org
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/redtux
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/redtux
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/redtux2000
footer:
  links:
  - label: pandainfo.org
    icon: fas fa-fw fa-link
    url: https://pandainfo.org
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/redtux
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/redtux
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/redtux2000
include:
- ".htaccess"
- _pages
exclude:
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG.md
- code-of-conduct.md
- config
- Gemfile
- Gemfile.lock
- Gruntfile.js
- gulpfile.js
- LICENSE*.md
- licenses
- log
- node_modules
- package.json
- Rakefile
- README.md
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: true
liquid:
  error_mode: strict
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-mentioji
- jekyll-include-cache
- jekyll-archives
- jekyll-avatar
- jekyll-github-metadata
- jekyll-octicons
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-mentioji
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
compress_html:
  clippings: all
  ignore:
    envs: development
