remote_theme: redtux/minimal-mistakes
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "de"
title: "panda!"
title_separator: "🐾"
name: &name "pandainfo.org"
description: &description "assoziation panda! 🐾 Verein zur Förderung des kritischen literarischen Diskurses"
logo: /assets/images/panda-avatar.png
og_image: /assets/images/panda-avatar.png
breadcrumbs: true
words_per_minute: 190
author:
  name: *name
  avatar: /assets/images/panda-avatar.png

collections:
  news:
    output: true
    permalink: /:collection/:path/
  books:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    permalink: /:collection/:path/
  about:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _books
  - scope:
      path: ""
      type: books
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "books"
  # _events
  - scope:
      path: ""
      type: events
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _about
  - scope:
      path: ""
      type: about
    values:
      layout: single
      author_profile: false
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
paginate: 5
timezone: Europe/Vienna

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
